services:
  pychan:
    image: pychan:1.0.0
    container_name: pychan
    ports:
      - 4433:4433
    volumes:
      - imagedir:/app/static/images
    deploy:
      restart_policy:
        condition: any

volumes:
  imagedir:
